before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev libpcre3-dev wget unzip 
language: c
compiler:
    - clang
    - gcc
dist: trusty
env:
  - NGX_AWS_MODULE=--add-module=$TRAVIS_BUILD_DIR
  - NGX_AWS_MODULE=--add-dynamic-module=$TRAVIS_BUILD_DIR
script: echo $TRAVIS_BUILD_DIR && ./travis_build.sh $NGX_AWS_MODULE
after_script: ldd /usr/lib64/nginx/modules/ngx_http_aws_auth_module.so
notifications:
  email:
    recipients:
      - eran.kornblau@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
